### ISSUE TITLE
需要 TradeInfo 解密的方法

### ISSUE THREAD

**Issue by renfu-her** [MingJSHK/laravel-newebpay#1]
目前需要 TradeInfo 解密的方法

**Comment by MingJSHK** [comment]
請參考
[HasEncryption.php](https://github.com/MingJSHK/laravel-newebpay/blob/main/src/Concerns/HasEncryption.php)
[BaseNewebPay](https://github.com/MingJSHK/laravel-newebpay/blob/main/src/BaseNewebPay.php)
如果想直接進行解碼
可使用
$newebpay->submitAndDecode("TradeInfo");
或是
$newebpay->decode($result['TradeInfo']);
